function compare_q(m, k, c, x0, v0, f, time)
    tic;
    
    [numerical_x, numerical_v] = numerical_q(m, k, c, x0, v0, f, time);
    [analytical_x, analytical_v] = analytical_q(m, k, c, x0, v0, f, time);

    plot_q( ...
        time, ...
        [numerical_x; numerical_v], ...
        total_energy(m, k, numerical_x, numerical_v), ...
        [analytical_x; analytical_v], ...
        total_energy(m, k, analytical_x, analytical_v) ...
    );

    toc;
end
